name: borderless
description: "For home sharing purposes"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  awesome_notifications: ^0.9.3+1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.0.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0
  flutter_secure_storage: ^9.0.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  http: ^1.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  just_audio: ^0.9.37
  jwt_decoder: ^2.0.1
  logger: ^2.2.0
  page_transition: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  photo_view: ^0.14.0
  popover: ^0.3.0
  provider: ^6.1.2
  record: ^5.0.5
  record_mp3: ^3.0.0
  retry: ^3.1.2
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  video_player: ^2.8.6
  chewie: ^1.8.1
  web_socket_channel: ^2.4.4
  reorderable_grid_view: ^2.2.6
  video_thumbnail: ^0.5.3
  restart_app: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/animated-bell.gif

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
